name: Build and push Docker images to Intelligence Packages
on:
  push:
  workflow_dispatch:
jobs:
  cloudflare_dyndns_docker-build-push:
    name: Build and push cloudflare-dyndns docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Intelligence Packages
        uses: docker/login-action@v1
        with:
          registry: packages.intelligence-modding.de
          username: "srendi"
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Lowercase repository owner
        run: |
          echo "REPO_OWNER=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: packages.intelligence-modding.de/p/cloudflaredyndns/containers/cloudflare-dyndns
      - name: Build and push image to Intelligence Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          context: ./
          push: true
          platforms: linux/amd64,linux/arm/v6
          tags: packages.intelligence-modding.de/p/cloudflaredyndns/containers/cloudflaredyndns:latest
          labels: ${{ steps.meta.outputs.labels }}
